# Parser labels
Parser - Core:
- changed-files:
  - any-glob-to-any-file: src/parser/core/**/*

Parser - AST:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/ast/**/*

Parser - BLM:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/blm/**/*

Parser - BLU:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/blu/**/*

Parser - BRD:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/brd/**/*

Parser - DNC:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/dnc/**/*

Parser - DRG:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/drg/**/*

Parser - DRK:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/drk/**/*

Parser - GNB:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/gnb/**/*

Parser - MCH:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/mch/**/*

Parser - MNK:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/mnk/**/*

Parser - NIN:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/nin/**/*

Parser - PCT:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/pct/**/*

Parser - PLD:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/pld/**/*

Parser - RDM:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/rdm/**/*

Parser - RPR:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/rpr/**/*

Parser - SAM:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/sam/**/*

Parser - SCH:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/sch/**/*

Parser - SGE:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/sge/**/*

Parser - SMN:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/smn/**/*

Parser - VPR:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/vpr/**/*

Parser - WAR:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/war/**/*

Parser - WHM:
- changed-files:
  - any-glob-to-any-file: src/parser/jobs/whm/**/*
